//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaSayfaSlider
    {
        public int ID { get; set; }
        public int sira { get; set; }
        public string photo_path { get; set; }
    }
}
