//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PegmerGirisimcileri
    {
        public int ID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string firma_adi { get; set; }
        public string faliyet_detayi { get; set; }
        public string web { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string faliyet_alani { get; set; }
    }
}
