//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnaSayfaHizmetler
    {
        public int ID { get; set; }
        public string adi { get; set; }
        public string hizmet_foto_path { get; set; }
    }
}
