//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tesisler()
        {
            this.Foto = new HashSet<Foto>();
        }
    
        public int ID { get; set; }
        public string adi { get; set; }
        public string kapak_foto { get; set; }
        public string map_url { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string aciklama { get; set; }
        public int turID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual OrganizasyonTuru OrganizasyonTuru { get; set; }
    }
}
